language: c

git:
  depth: 1
  quiet: true

install:
  - curl -o /tmp/mdbook.tar.gz
        -L 'https://github.com/rust-lang-nursery/mdBook/releases/download/v0.3.0/mdbook-v0.3.0-x86_64-unknown-linux-gnu.tar.gz'
    && tar xf /tmp/mdbook.tar.gz -C ~/bin

script:
  - mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: book
  github-token: $GH_DEPLOY_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
