[package]
name = "handle"
version = "0.1.0"
authors = ["Jay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.1"
reqwest = "0.9.x"
csv = "1.1.1"
serde_derive = "1.0.103"
