[package]
name = "r-w"
version = "0.1.0"
authors = ["Jay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
same-file = "1.0.5"
memmap = "0.7.0"
