[package]
name = "clib"
# version = "0.1.0"
authors = ["Jay"]
edition = "2018"
version = "1.0.2"
build = "build.rs"

[build-dependencies]
cc = "1"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
