[package]
name = "para"
version = "0.1.0"
authors = ["Jay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.2.1"
rand = "0.7.2"
error-chain = "0.12.1"
glob = "0.3.0"
image = "0.23.0-preview.0"
