[package]
name = "re"
version = "0.1.0"
authors = ["Jay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.x"
error-chain = "0.12.1"
tempfile = "3.1.0"
