[package]
name = "cc_auto_build_c_lib"
version = "0.1.0"
authors = ["yujinliang <285779289@qq.com>"]
edition = "2018"
build="build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.53"

[dependencies]
