[package]
name = "vecsum"
version = "0.1.0"
authors = ["Jay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"
nalgebra = "0.19.0"
